language: python
os: linux
dist: bionic

python:
  - "3.8"

cache:
  directories:
  - "$HOME/db/"
  pip: true

env:
  global:
    #- secure: "av7eQ6L/TybtjAnhrtGVR9ja6dZMLLSHK8fljuzl4MdYv4/OI0ftTXm2o6JZNQ6jfwoWu3kRQCcrWYXLEPvWB4qaAcjyd9Wohm/1U1zcgOK6Gb3zIohKkDW0Vc5ciZp8joDrVMKGNgh49IPElRUYUIZAC/uWKYAcKZQhzo0UM5v1zIOBrL/WoRZ2KaOwva+vPbIlUOSwe7k0mg4aJghD7YqJwmb81H/TW2wP2xvksnnF5fKW8ODGCpRK0flgftxVx1tZyIVgGfe4ach2PLKaZa0F24ifyRBdPNAeCXGsC/9EcPePlJXuVVb91jmdUhq9Zcc1NZOqOGhvGUKKkvcizG0JgCgu9/DgahxKLiu2h20a+mvKGATZm2Q8FF4YjHpNMyeF3eUyTwrjIdS7+/7XD6igg/zD/i9jaXPwQEFvgYWCuAsqcAXQHPAUM41w3ifqmDlJhwmPIXsdf+OlPCvlhEiZBZWXmZjK96EMFRtdsdbt2RcC2jHXLeu8eCrAkoebyi/jXO7e+w9K+40U1eszH3diBSz7uCJvsyL0m0mZ1cq88nCjDl/yDeBiuCp+1MzlK0axeLj/YxUvgAEQnhGUEXm/Iyc6Z0JJaBS5SxCKMTEL9R7ApPtoqGdW88OWFVanEvNTJK+MhzUcMJuOqaSNY2mDkYQW5/njjNrWjFCFk64="
    - GH_TOKEN: "${GH_TOKEN}"
    - GIT_NAME: "TravisCI"
    - GIT_EMAIL: "travis@travis-ci.org"
    - TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG} # Import-External-Sources/hosts-bait-sites
    - GIT_BRANCH: ${TRAVIS_BRANCH} # master
    - TZ: UTC
    - PYFUNCEBLE_AUTO_CONFIGURATION: YES
    - DEBUG_PYFUNCEBLE_ON_SCREEN: true
    #- PYFUNCEBLE_CONFIG_DIR: ${TRAVIS_BUILD_DIR}/dev-tools/
    #- PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

addons:
  mariadb: '10.4'
  apt:
    update: true
    packages:
    - dos2unix
    - msttcorefonts
    - lsof
    - pdns-recursor

install:
  - pip3 install --upgrade pip
  - pip3 install -r "${TRAVIS_BUILD_DIR}/requirements.txt"

git:
  depth: 2

jobs:
  fast_finish: true

script:
  - sudo systemctl restart mysql.service
  - sudo mysql -u root -h localhost -e "CREATE DATABASE PyFunceble DEFAULT CHARACTER
    SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  - sudo mysql -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
  - sudo mysql -u root -h localhost -e "CREATE USER 'PyFunceble'@'localhost' IDENTIFIED
    BY 'PyFunceble';"
  - sudo mysql -u root -h localhost -e "GRANT ALL PRIVILEGES ON *.* TO 'PyFunceble'@'localhost';"
  - sudo mysql --user=PyFunceble --password=PyFunceble PyFunceble < "${TRAVIS_BUILD_DIR}/db/pyfunceble.sql"
  # We put both in same statement so that if one fails the whole test result will fail.
  - bash dev-tools/DataTesting.sh && mkdir -p "${TRAVIS_BUILD_DIR}/db/" \
    && sudo mysqldump --user=PyFunceble --password=PyFunceble --opt PyFunceble
    > "${TRAVIS_BUILD_DIR}/db/pyfunceble.sql"
